config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index'

  resources :events, only: [:create, :edit, :update, :destroy, :index] do
    collection do
      get :data_table
    end

    member do
      get :data_table
    end
  end

  resources :vacation_requests, only: [:create, :edit, :update, :destroy, :index]

  resources :feedbacks, only: [:create]

  resources :rooms, only: [:index]

  mount ActionCable.server => '/cable'

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    resources :feedbacks, only: [:index] do
      member do
        patch :dismissed
        patch :in_progress
        patch :resolved
      end
    end

    resources :projects, param: :slug, sexcept: [:show, :new, :update] do
      member do
        get :report
      end

      collection do
        post :add_user
        patch :remove_user
      end
    end

    resources :vacation_requests, only: [:index] do
      collection do
        post :accept
        post :decline
        post :holiday
      end
    end

    resources :users, except: [:new, :create] do
      collection do
        post :add_rate
      end

      member do
        post :update_project
        patch :remove_project
        patch :set_limit
        post :add_project
        get :event_table, controller: :events
      end
    end

    resources :reports, only: [:index]
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController

    add_breadcrumb 'Admin', :admin_dashboard_path

    def index
      if VacationRequest.pending.any?
        @vacation_requests = VacationRequest.pending.includes :user
        flash.now[:partial] = 'admin/dashboard/pending_vacations'
      end
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/_pending_vacations.html.erb
<div class="alert bg-danger">
  The following people have pending vacation requests: <br>

  <% @vacation_requests && @vacation_requests.each do |vr| %>
    <ul>
      <li><%= link_to vr.user.name, edit_admin_user_path(vr.user) %></li>
    </ul>
  <% end %>
</div>

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= link_to 'Feedbacks', admin_feedbacks_path, class: 'btn btn-lg btn-default btn-block', role: 'button' %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= link_to 'Projects', admin_projects_path, class: 'btn btn-lg btn-default btn-block', role: 'button' %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= link_to 'Users', admin_users_path, class: 'btn btn-lg btn-default btn-block', role: 'button' %>
  </div>
</div>


<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= link_to 'Vacations', admin_vacation_requests_path, class: 'btn btn-lg btn-default btn-block', role: 'button' %>
  </div>
</div>

<div class="row margin-top-20">
  <div id="fromDate" class="col-md-offset-3 col-md-3 col-xs-6">
    <%= render partial: 'application/datepicker', locals: { placeholder: 'From...' } %>
  </div>

  <div id="toDate" class="col-md-3 col-xs-6">
    <%= render partial: 'application/datepicker', locals: { placeholder: 'To...' } %>
  </div>
</div>

<div class="row margin-top-20">
  <div class="col-md-offset-3 col-md-6 col-xs-12">
    <table id="eventsTable"
           class="table table-striped table-bordered table-responsive"
           data-source="<%= admin_reports_path format: 'json' %>">

      <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th>Hours</th>
      </tr>
      </thead>

      <tbody>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-12">
    <%= link_to 'Export XLSX', '#', class: 'btn btn-lg btn-success btn-block', role: 'button',
                id: 'exportXls', data: { source: admin_reports_path(format: :xlsx) } %>
  </div>
</div>