config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index'

  resources :events, only: [:create, :edit, :update, :destroy, :index] do
    collection do
      get :data_table
    end

    member do
      get :data_table
    end
  end

  resources :vacation_requests, only: [:create, :edit, :update, :destroy, :index]

  resources :feedbacks, only: [:create]

  resources :rooms, only: [:index]

  mount ActionCable.server => '/cable'

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    resources :feedbacks, only: [:index] do
      member do
        patch :dismissed
        patch :in_progress
        patch :resolved
      end
    end

    resources :projects, param: :slug, sexcept: [:show, :new, :update] do
      member do
        get :report
      end

      collection do
        post :add_user
        patch :remove_user
      end
    end

    resources :vacation_requests, only: [:index] do
      collection do
        post :accept
        post :decline
        post :holiday
      end
    end

    resources :users, except: [:new, :create] do
      collection do
        post :add_rate
      end

      member do
        post :update_project
        patch :remove_project
        patch :set_limit
        post :add_project
        get :event_table, controller: :events
      end
    end

    resources :reports, only: [:index]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    respond_to do |format|
      format.json do
        pagination = {
            next: root_url(date: @date + 1.month, format: :json),
            previous: root_url(date: @date - 1.month, format: :json)
        }

        render json: Event.date_stats_from_beginning_of_month(@date, current_user).merge(pagination)
      end

      format.html { }
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def events_title
    "Work on #{@date.strftime('%a, %b %d %Y')}, Total: #{hours_worked}"
  end

  def event_duration(event)
    distance_of_time_in_words event.duration
  end

  def project_name(event)
    event.project ? event.project.name : 'Project N/A'
  end

  def events_at(date=@date)
    current_user.events.at date
  end

  def hours_worked(date=@date)
    distance_of_time_in_words events_at(date).total
  end
end

app/views/welcome/_event_form.html.erb
<div class="daily-events-container">
  <div class="row">
    <%= form_for event, html:{class: 'col s12'}, namespace: event.persisted? ? 'e' : 'n', remote: true do |f| %>
      <div id="date-input-container">
        <%= react_component('DateInput', date: @date) %>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :description, class: "materialize-textarea validate #{validation_class(event, :description)}" %>
          <%= f.label 'Description' %>
          <%= validation_message(event, :description) %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <p class="range-field">
            <%= f.number_field :hours, min: 0, max: 12, step: 1, class: "validate #{validation_class(event, :hours)}" %>
            <%= f.label 'Hours' %>
            <%= validation_message(event, :hours) %>
          </p>
        </div>
        <div class="input-field col s6">
          <p class="range-field">
            <%= f.number_field :minutes, min: 0, max: 45, step: 15, class: "validate #{validation_class(event, :minutes)}" %>
            <%= f.label 'Minutes' %>
            <%= validation_message(event, :minutes) %>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= f.collection_select :project_id, current_user.projects, :id, :name, {}, {class: "validate #{validation_class(event, :project_id)}"} %>
          <%= f.label 'Project' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s8">
          <%= f.check_box :ot, include_hidden: false, class: "validate #{validation_class(event, :ot)}" %>
          <%= f.label :ot, class: 'label' do %>
            Overtime
          <% end %>
          <%= validation_message(event, :ot) %>
        </div>
        <div class="input-field col s1">
          <a class="right-align btn-floating btn-medium waves-effect waves-light red" id="reset-form">
            <i class="material-icons">replay</i>
          </a>
        </div>
        <div class="input-field col s2">
          <%= f.submit 'Submit', data: { disable_with: 'Submitting...' }, class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/_vacation_form.html.erb
<div class="daily-events-container">
  <div class="row">
    <%= form_for vacation, html:{class: 'col s12'}, namespace: vacation.persisted? ? 'e' : 'n', remote: true do |f| %>
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :vacation_from, class: 'datepicker' %>
          <%= f.label 'Vacation from' %>
          <%= validation_message(vacation, :vacation_from) %>
        </div>
        <div class="input-field col s6">
          <%= f.text_field :vacation_to, class: 'datepicker' %>
          <%= f.label 'Vacation to' %>
          <%= validation_message(vacation, :vacation_to) %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
            <%= f.text_area :reason, class: "materialize-textarea" %>
            <%= f.label 'Reason' %>
            <div class="vacation-reason">
              <%= validation_message(vacation, :reason) %>
            </div>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s9">
          <%= f.check_box :paid, include_hidden: false %>
          <%= f.label :paid, class: 'label' do %>
            Paid
          <% end %>
        </div>
        <div class="input-field col s3">
          <%= f.submit 'Submit', data: { disable_with: 'Submitting...' }, class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<%= react_component('Calendar', eventsUrl: events_path(format: 'json'), url: root_path(format: 'json', date: @date)) %>
<%= react_component('VacationRequests', requestsUrl: vacation_requests_path(format: 'json'), vacationDays: current_user.vacation_days_left) %>

<div id="new-event-form-container" class="modal">
  <div class="modal-content">
    <%= render partial: 'welcome/event_form', locals: { event: current_user.events.new(hours: 8) } %>
  </div>
</div>

<script>
  $( document ).ready(function() {
    $(document).on('click', '#n_new_event  #reset-form', function () {
      $('#new-event-form-container .modal-content')
          .html('<%= escape_javascript render(partial: 'welcome/event_form', locals: { event: current_user.events.new(hours: 8) }) %>');
      $('#new-event-form-container select').material_select('destroy');
      $('#new-event-form-container select').material_select();
      window.ReactRailsUJS.unmountComponents("#date-input-container");
      window.ReactRailsUJS.mountComponents("#date-input-container");
    });

    $(document).on('click', "form[id^='e_edit_event']  #reset-form", function () {
      var url = ($( "form[id^='e_edit_event']").attr('action')) + '/edit';
      $('#event-form-container').data('eventPath', url);
      $.ajax({
        url: $('#event-form-container').data('eventPath'),
        method: 'GET',
        dataType: 'html',
        cache: false,
        success: function(data) {
          $('#event-form-container .modal-content').html(data);
          $('#event-form-container select').material_select('destroy');
          $('#event-form-container select').material_select();
        },
        error: function(xhr, status, err) {
          console.error(status, err.toString());
        }.bind(this)
      });
    });
  });
</script>

<div id="new-vacation-form-container" class="modal">
  <div class="modal-content">
    <%= render partial: 'welcome/vacation_form', locals: { vacation: current_user.vacation_requests.new } %>
  </div>
</div>

<div id="event-form-container" class="modal">
  <div class="modal-content"></div>
</div>

<div id="vacation-form-container" class="modal">
  <div class="modal-content"></div>
</div>

<div id="feedback-modal" class="modal">
  <div class="modal-content">
    <%= render partial: 'feedbacks/form', locals: { feedback: Feedback.new } %>
  </div>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="right-align btn-floating btn-large waves-effect waves-light red modal-trigger b1" href="#calendar-modal">
    <i class="material-icons">today</i>
  </a>
  <a class="right-align btn-floating btn-large waves-effect waves-light red modal-trigger b2" href="#feedback-modal">
    <i class="material-icons">comment</i>
  </a>
</div>


<div id="page-bottom" style="padding-bottom: 55px"></div>