config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index'

  resources :events, only: [:create, :edit, :update, :destroy, :index] do
    collection do
      get :data_table
    end

    member do
      get :data_table
    end
  end

  resources :vacation_requests, only: [:create, :edit, :update, :destroy, :index]

  resources :feedbacks, only: [:create]

  resources :rooms, only: [:index]

  mount ActionCable.server => '/cable'

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    resources :feedbacks, only: [:index] do
      member do
        patch :dismissed
        patch :in_progress
        patch :resolved
      end
    end

    resources :projects, param: :slug, sexcept: [:show, :new, :update] do
      member do
        get :report
      end

      collection do
        post :add_user
        patch :remove_user
      end
    end

    resources :vacation_requests, only: [:index] do
      collection do
        post :accept
        post :decline
        post :holiday
      end
    end

    resources :users, except: [:new, :create] do
      collection do
        post :add_rate
      end

      member do
        post :update_project
        patch :remove_project
        patch :set_limit
        post :add_project
        get :event_table, controller: :events
      end
    end

    resources :reports, only: [:index]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include FriendlyId
  friendly_id :name, :use => [:slugged]

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :user_projects, dependent: :destroy
  has_many :events, dependent: :nullify
  has_many :users, through: :user_projects

  def to_keen
    {
        name: name
    }
  end

  class << self
    def empty
      OpenStruct.new(id: nil, name: 'Project N/A')
    end

    def events_for_projects(user:, date:)
      (user.projects.all + [Project.empty]).map do |project|
        events = user.events.at(date).where(project_id: project.id).map do |e|
          {
              duration: e.duration / 3600.0,
              description: e.description,
              vacation: e.gefroren,
              total: e.amount,
              url: Rails.application.routes.url_helpers.edit_event_path(e),
              event_url: Rails.application.routes.url_helpers.event_path(e),
              id: e.id
          }
        end

        { project.name => events }
      end.reduce(:merge)
    end
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < BaseController
    respond_to :html
    respond_to :js, only: [ :add_user, :create ]

    add_breadcrumb 'Admin', :admin_dashboard_path
    add_breadcrumb 'Projects', :admin_projects_path

    before_action :load_project, only: [:edit, :report, :remove_user]

    include DateParser

    def index
      respond_to do |format|
        format.json do
          render json: ProjectDataTable.new(view: view_context, relation: Project)
        end

        format.html {}
      end
    end

    def report
      respond_to do |format|
        format.html do
          redirect_to edit_admin_project_path(@project.slug)
        end

        format.js {}
      end
    end

    def create
      @project = Project.new create_project_params
      @success = @project.save
      respond_with @project, location: -> { admin_projects_path }
    end

    def edit
      add_breadcrumb "Editing Project: #{@project.name}", edit_admin_project_path(@project)
    end

    def add_user
      @user_project = UserProject.new add_user_params
      @success = @user_project.save
      respond_with @user_project, location: -> { edit_admin_project_path @user_project.project }
    end

    def remove_user
      UserProject.where(project_id: @project.id, user_id: params[:user_id]).destroy_all
      flash[:notice] = 'Person successfully removed'
    rescue
      flash[:alert] = 'Unable to remove the person from the project'
    ensure
      redirect_to edit_admin_project_path(params[:slug])
    end

    private
    def add_user_params
      rates_attributes = [ :hourly_rate, :hourly_rate_ot, :available_from, :available_until ]
      params.require(:user_project).permit(:user_id, :project_id, rates_attributes: rates_attributes)
    end

    def create_project_params
      params.require(:project).permit(:name)
    end

    def load_project
      @project = Project.find_by_slug params[:slug]
    end
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
  def users_to_add(project=nil)
    project ||= (@project || @user_project.project)
    User.where.not id: project.users.pluck(:id)
  end

  def user_project
    @user_project ||= (@project || @user).user_projects.new rescue UserProject.new
  end

  def user_project_rates
    @user_project_rates ||= if user_project.rates.empty?
      user_project.rates.new
    else
      user_project.rates
    end
  end

  #
  # @param user_project [UserProject] getting rates
  #
  def project_details(user_project)
    return @rates[user_project.id] if defined?(@rates) && @rates[user_project.id]

    @rates ||= {}

    ret = Hashie::Mash.new({}, '-')

    if user_project.payable?
      ret.hourly_rate = user_project.current_rate.hourly_rate
      ret.hourly_rate_ot = user_project.current_rate.hourly_rate_ot
      ret.available_from = user_project.current_rate.available_from
    end

    @rates[user_project.id] = ret
  end

  def user_form_params
    { users: users_to_add, user_project: user_project, user_project_rates: user_project_rates }
  end
end

app/views/admin/projects/_add_user.html.erb
<div class="modal fade" id="addUser" tabindex="-1" role="dialog"
     aria-labelledby="addUserLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="addUserLabel">Add User</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'user_form', locals: user_form_params %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/_project_form.html.erb
<%= bootstrap_form_for Project.new,  url: { action: :create } do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Create' %>
<% end %>

app/views/admin/projects/_project_table.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Project Name</th>
    <th>Create At</th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, edit_admin_project_path(project) %></td>
      <td><%= project.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/projects/_projects_table.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Project Name</th>
    <th>Create At</th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, edit_admin_project_path(project) %></td>
      <td><%= project.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/projects/_resource_form.html.erb
<%= bootstrap_form_for @project || Project.new,  url: { action: :create }, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Create', data: { disable_with: 'Submitting...' } %>
<% end %>

app/views/admin/projects/_user_form.html.erb
<%= bootstrap_form_for user_project, url: { action: :add_user }, remote: true do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.collection_select :user_id, users, :id, :name %>

  <div class="form-group">
    <%= check_box_tag :userRateToggle %>
    <%= label_tag :userRateToggle, 'Differ rate to User default' %>
  </div>

  <div id="userRate">
    <%= f.fields_for :rates, user_project_rates do |rate| %>
      <%= rate.number_field :hourly_rate, step: :any %>
      <%= rate.number_field :hourly_rate_ot, step: :any %>
      <%= rate.text_field :available_from, class: 'datepicker' %>
      <%= rate.text_field :available_until, class: 'datepicker' %>
    <% end %>
  </div>

  <%= f.submit 'Submit', data: { disable_with: :submit } %>
<% end %>

<%= javascript_tag do %>
  $('input.datepicker').customDatepicker({'orientation': 'bottom auto' });
<% end %>

app/views/admin/projects/_user_info.html.erb
<div class="list-group-item">
  <div class="row">
    <div class="col-xs-10">
      <h4 class="list-group-item-heading"><%= link_to user.name, edit_admin_user_path(user.id) %></h4>
      <p class="list-group-item-text">Hourly Rate: <%= project_details(user_project).hourly_rate %></p>
      <p class="list-group-item-text">Hourly Rate OT: <%= project_details(user_project).hourly_rate_ot %></p>
    </div>

    <div class="col-xs-2">
      <%= link_to remove_user_admin_projects_path(user_id: user.id, slug: @project.slug), remove_user_options do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/projects/add_user.js.erb
<% if @success %>
  window.location = window.location;
<% else %>
  $('#addUser .modal-body')
          .html('<%= escape_javascript render(partial: 'user_form', locals: user_form_params) %>');
<% end %>

app/views/admin/projects/create.js.erb
<% if @success %>
  window.location = window.location;
<% else %>
  $('.modal.in .modal-body')
        .html('<%= escape_javascript render(partial: 'resource_form') %>');
<% end %>

app/views/admin/projects/edit.html.erb
<div class="row">
  <%= render partial: 'admin/projects/report/index' %>
</div>

<% content_for :list_items do %>
  <% @project.user_projects.includes(:user).each do |user_project| %>
    <%= render partial: 'user_info', locals: { user: user_project.user, user_project: user_project } %>
  <% end %>
<% end %>

<% content_for :panel_title, @project.name.capitalize %>
<% content_for :custom_modal_id, 'addUser' %>

<% content_for :custom_modal do %>
  <%= render partial: 'application/modal',
             locals: { resource_name: 'User', resource_id: 'User', body: 'user_form', form_params: user_form_params } %>
<% end %>

<%= render file: 'application/panel', locals: { list_group_id: 'usersForProject' } %>

app/views/admin/projects/index.html.erb
<div class="row margin-top-20">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
        <table id="projectsTable"
               class="table table-striped table-bordered table-responsive"
               data-source="<%= admin_projects_path format: 'json' %>">

            <thead>
            <tr>
                <th>Name</th>
                <th>Created At</th>
            </tr>
            </thead>

            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="center">
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#add<%= resource_title.to_cc %>">
        Add Project <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
</div>

<%= render partial: 'modal',
           locals: { resource_name: resource_title, resource_id: resource_title.to_cc, body: 'resource_form' } %>

app/views/admin/projects/report.js.erb
$('#report-form').html('<%= escape_javascript render(partial: 'admin/projects/report/form') %>');
$('#report-content').html('<%= escape_javascript render(partial: 'admin/projects/report/content') %>');
$('.report-container .datepicker').customDatepicker({});