config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index'

  resources :events, only: [:create, :edit, :update, :destroy, :index] do
    collection do
      get :data_table
    end

    member do
      get :data_table
    end
  end

  resources :vacation_requests, only: [:create, :edit, :update, :destroy, :index]

  resources :feedbacks, only: [:create]

  resources :rooms, only: [:index]

  mount ActionCable.server => '/cable'

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    resources :feedbacks, only: [:index] do
      member do
        patch :dismissed
        patch :in_progress
        patch :resolved
      end
    end

    resources :projects, param: :slug, sexcept: [:show, :new, :update] do
      member do
        get :report
      end

      collection do
        post :add_user
        patch :remove_user
      end
    end

    resources :vacation_requests, only: [:index] do
      collection do
        post :accept
        post :decline
        post :holiday
      end
    end

    resources :users, except: [:new, :create] do
      collection do
        post :add_rate
      end

      member do
        post :update_project
        patch :remove_project
        patch :set_limit
        post :add_project
        get :event_table, controller: :events
      end
    end

    resources :reports, only: [:index]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects
  has_many :events, dependent: :destroy
  has_many :evaluated_vacation_requests, class_name: 'VacationRequest', foreign_key: :admin_id
  has_many :feedbacks
  has_many :messages

  include Oauth
  include Payable
  include Vacation

  devise :database_authenticatable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  validate :has_company_email_address?
  validates_numericality_of :vacation_limit, greater_than_or_equal_to: 0
  before_save :set_admin_flag

  def name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def to_keen
    {
      name: name,
      email: email,
      created_at: created_at,
      ip: current_sign_in_ip
    }
  end

  def report(project:, from:, to:)
    query = <<-SQL
      SELECT string_agg('[' || round(e.hours + e.minutes / 60.0, 1) || '] ' || e.description, '\n ') as description
            ,e.worked_at FROM events as e
      WHERE user_id = #{id} AND e.project_id = #{project.id.to_i}
      AND worked_at >= '#{from.beginning_of_day.strftime '%Y-%m-%d %H:%M:%S'}'
      AND worked_at <= '#{to.end_of_day.strftime '%Y-%m-%d %H:%M:%S'}'
      GROUP BY e.worked_at
      ORDER BY e.worked_at ASC
    SQL

    decimal_mapper = ->(d) { d[0] == '0' ? '' : ".#{d}"  }

    ActiveRecord::Base.connection.execute(query).to_a.map do |day|
      day['description'] = day['description'].split(/\n/).map do |event_description|
        event_description.sub(/\[(\d+)\.(\d+)\]/) do
          "[#{Regexp.last_match[1]}#{decimal_mapper.call(Regexp.last_match[2])}h]"
        end
      end.join('<br/>').html_safe

      day
    end || []
  end

  private
  def set_admin_flag
    admins = Figaro.env.admins.split(',').map &:strip
    address = Mail::Address.new email

    self.admin = admins.include? address.local

    self
  end

  def has_company_email_address?
    address = Mail::Address.new email
    unless address.domain == "#{Figaro.env.email_domain}.com"
      errors.add(:email, "You're not welcome here with a #{address.domain} email domain.")
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController

    respond_to :html
    respond_to :js, only: [ :add_rate, :add_project, :update_project ]

    add_breadcrumb 'Admin', :admin_dashboard_path
    add_breadcrumb 'Users', :admin_users_path

    def index
      respond_to do |format|
        format.json do
          render json: UserDataTable.new(view: view_context, relation: User)
        end

        format.html { }
      end
    end

    #
    # [TODO] add some error handling here.
    #
    def set_limit
      vacation_limit = VacationLimit.find_or_initialize_by(user_id: params[:id], year: Date.today.year)
      vacation_limit.limit = params[:user][:vacation_limit].to_i
      vacation_limit.save

      redirect_to edit_admin_user_path params[:id]
    end

    def edit
      @user = User.find params[:id]
      unless @user.payable?
        flash.now[:alert] = "#{@user.name} does not have a base rate. Please add one."
      end

      add_breadcrumb "Editing User: #{@user.name}", edit_admin_user_path(@user.id)
    end

    def add_rate
      @rate = Rate.new add_rate_params
      @success = @rate.save
      respond_with @rate, location: edit_admin_user_path(add_rate_params[:payable_id])
    end

    def add_project
      @user = User.find params[:id]
      @user_project = @user.user_projects.new add_project_params
      @success = @user_project.save
      respond_with @user_project, location: -> { edit_admin_user_path @user_project.user }
    end

    def update_project
      @user_project = UserProject.find add_rate_params[:payable_id]
      @rate = Rate.new add_rate_params
      @success = @rate.save
      respond_with @rate, location: edit_admin_user_path(params[:id])
    end

    def remove_project
      UserProject.where(project_id: params[:project_id], user_id: params[:id]).destroy_all
      flash[:notice] = 'Project successfully removed'
    rescue
      flash[:alert] = 'Unable to remove project'
    ensure
      redirect_to edit_admin_user_path(params[:id])
    end

    private
    def add_project_params
      rates_attributes = [ :hourly_rate, :hourly_rate_ot, :available_from, :available_until ]
      params.require(:user_project).permit(:project_id, rates_attributes: rates_attributes)
    end

    def add_rate_params
      params.require(:rate).permit :payable_id, :payable_type, :available_from,
                                   :available_until, :hourly_rate, :hourly_rate_ot
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def rate_resource
    @rate ||= @user.rates.new
  end

  def projects_to_add(user=nil)
    user ||= (@user || @user_project.user)
    Project.where.not id: user.projects.pluck(:id)
  end

  def project_form_params
    { projects: projects_to_add, user_project: user_project, user_project_rates: user_project_rates }
  end
end

app/views/admin/users/_edit_project_form.html.erb
<%= bootstrap_form_for @rate || user_project.rates.next(user_project.current_rate) , url: { action: :update_project }, remote: true do |f| %>

  <h4>Edit rates for project: <%= project.name %></h4>
    <%= f.hidden_field :payable_id %>
    <%= f.hidden_field :payable_type %>
    <%= f.number_field :hourly_rate, step: :any %>
    <%= f.number_field :hourly_rate_ot, step: :any %>
    <%= f.text_field :available_from, class: 'datepicker' %>
    <%= f.text_field :available_until, class: 'datepicker' %>

    <%= f.submit 'Submit', data: { disable_with: 'Submitting...' } %>
<% end %>

<%= javascript_tag do %>
    $('input.datepicker').customDatepicker({'orientation': 'bottom auto'});
<% end %>

app/views/admin/users/_event_table.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-12">
    <table id="userEventsTable"
           class="table table-striped table-bordered table-responsive"
           data-source="<%= event_table_admin_user_path format: 'json' %>">

      <thead>
      <tr>
        <th>Project Name</th>
        <th>Amount</th>
        <th>Hours</th>
        <th class="visible-lg">Minutes</th>
        <th class="visible-lg">Worked At</th>
        <th class="visible-lg">Description</th>
      </tr>
      </thead>

      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/_project_form.html.erb
<%= bootstrap_form_for user_project, url: { action: :add_project, params: { id: @user.id } }, remote: true do |f| %>
  <%= f.collection_select :project_id, projects, :id, :name %>

  <div class="form-group">
    <%= check_box_tag :userRateToggle %>
    <%= label_tag :userRateToggle, 'Differ rate to User default' %>
  </div>

  <div id="userRate">
    <%= f.fields_for :rates, user_project_rates do |rate| %>
      <%= rate.number_field :hourly_rate, step: :any %>
      <%= rate.number_field :hourly_rate_ot, step: :any %>
      <%= rate.text_field :available_from, class: 'datepicker' %>
      <%= rate.text_field :available_until, class: 'datepicker' %>
    <% end %>
  </div>

  <%= f.submit 'Submit', data: { disable_with: :submit } %>
<% end %>

<%= javascript_tag do %>
  $('#userRate').find('input.datepicker').customDatepicker({'orientation': 'bottom auto' });
<% end %>

app/views/admin/users/_project_info.html.erb
<div class="list-group-item" id="projectForUser<%= project.id %>">
  <div class="row">
    <div class="col-xs-8">
      <h4 class="list-group-item-heading"><%= link_to project.name, edit_admin_project_path(project) %></h4>
      <p class="list-group-item-text">Hourly Rate: <%= project_details(user_project).hourly_rate %></p>
      <p class="list-group-item-text">Hourly Rate OT: <%= project_details(user_project).hourly_rate_ot %></p>
      <p class="list-group-item-text">Available From: <%= project_details(user_project).available_from %></p>
    </div>

    <% content_for :custom_modal_id, "addProjectUpdate#{project.id}", flush: true %>

    <% content_for :custom_modal, nil, flush: true do %>
        <%= render partial: 'application/modal', locals: {
                                                       form_params: {
                                                               project: project, user_project: user_project
                                                       },
                                                       resource_name: "ProjectUpdate#{project.id}",
                                                       resource_id: "ProjectUpdate#{project.id}",
                                                       body: 'edit_project_form' } %>
    <% end %>

    <div class="col-xs-2">
      <button type="button" class="btn btn-default" data-toggle="modal" data-target="#<%= yield :custom_modal_id %>">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
      </button>
    </div>

    <%= yield :custom_modal %>

    <div class="col-xs-2">
      <%= link_to remove_project_admin_user_path(@user, project_id: project.id), remove_options do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/_projects.html.erb
<% content_for :list_items do %>
  <!-- Making sure block is not empty -->
  <% @user.user_projects.includes(:project).each do |user_project| %>
    <%= render partial: 'project_info', locals: { project: user_project.project, user_project: user_project } %>
  <% end %>
<% end %>

<% content_for :custom_modal_id, 'addProject', flush: true  %>

<% content_for :custom_modal, nil, flush: true do %>
  <%= render partial: 'application/modal',
             locals: { resource_name: 'Project', resource_id: 'Project', body: 'project_form', form_params: project_form_params } %>
<% end %>

<% content_for :panel_title, "Projects for: #{@user.name}" %>

<%= render file: 'application/panel', locals: { list_group_id: 'projectsForUser' } %>

app/views/admin/users/_rate_info.html.erb
<div class="list-group-item" id="rateForUser<%= rate.id %>">
  <div class="row">
    <div class="col-xs-10">
      <h4 class="list-group-item-heading"> Rate (<%= rate.hourly_rate %>/<%= rate.hourly_rate_ot %>)</h4>
      <p class="list-group-item-text">Available From: <%= rate.available_from %></p>
      <p class="list-group-item-text">Available Until: <%= rate.available_until %></p>
    </div>
  </div>
</div>

app/views/admin/users/_users_table.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>User</th>
    <th>Email</th>
    <th>Joined Us</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, edit_admin_user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.asctime %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/_vacation_limit_form.html.erb
<%= bootstrap_form_for @user, layout: :inline, url: { action: :set_limit }, html: {style: 'display: inline;'} do |f| %>
  <%= f.number_field :vacation_limit, hide_label: true %>
  <%= f.submit 'Go!' %>
<% end %>

app/views/admin/users/_vacations.html.erb
<div class="row" id="vacationWrapper">
  <div class="col-lg-offset-3 col-lg-6 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h4><%= "Paid Vacation Days Left: #{@user.vacation_days_left}" %></h4></div>
      <div class="panel-heading desktop"><h4>Paid Vacation Days Limit: <%= render partial: 'vacation_limit_form' %></h4></div>

      <div class="list-group" id=vacationForUser>
        <% @user.vacation_requests.pending.each do |vacation| %>
          <div class="list-group-item" id="vacationInfo<%= vacation.id %>">
            <div class="row">
              <%= render partial: 'admin/users/vacation_info', locals: { vacation: vacation } %>

              <div class="approve-button">
                <%= link_to accept_admin_vacation_requests_path(vacation_id: vacation.id), remove_options(method: :post) do %>
                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <% end %>
              </div>

              <div class="closing-button">
                <%= link_to decline_admin_vacation_requests_path(vacation_id: vacation.id), remove_options(method: :post) do %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

        <% @user.vacation_requests.approved.this_year.each do |vacation| %>
          <div class="list-group-item" id="vacationInfo<%= vacation.id %>">
            <div class="row">
              <%= render partial: 'admin/users/vacation_info', locals: { vacation: vacation } %>
            </div>
          </div>
        <% end %>

        <% @user.vacation_requests.declined.this_year.each do |vacation| %>
          <div class="list-group-item" id="vacationInfo<%= vacation.id %>">
            <div class="row">
              <%= render partial: 'admin/users/vacation_info', locals: { vacation: vacation } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/add_project.js.erb
<% if @success %>
  window.location = window.location;
<% else %>
  $('#addProject').find('.modal-body')
          .html('<%= escape_javascript render(partial: 'project_form', locals: project_form_params) %>');
<% end %>

app/views/admin/users/add_rate.js.erb
<% if @success %>
  window.location = window.location;
<% else %>
  $('#addRate').find('.modal-body')
          .html('<%= escape_javascript render(partial: 'rate_form') %>');
<% end %>

app/views/admin/users/edit.html.erb
<%= render partial: 'projects' %>
<%= render partial: 'rates' %>
<%= render partial: 'vacations' %>

<% unless @user.events.empty? %>
  <%= render partial: 'event_table' %>
<% end %>

app/views/admin/users/index.html.erb
<div class="row margin-top-20">
    <div class="col-md-offset-2 col-md-8 col-xs-12">
        <table id="projectsTable"
               class="table table-striped table-bordered table-responsive"
               data-source="<%= admin_users_path format: 'json' %>">

            <thead>
            <tr>
                <th>User</th>
                <th>Email</th>
                <th>Joined Us</th>
            </tr>
            </thead>

            <tbody>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/users/update_project.js.erb
<% if @success %>
  window.location = window.location;
<% else %>
  $('.modal.in .modal-body')
      .html('<%= escape_javascript render(locals: {user_project: @user_project, project: @user_project.project}, partial: 'edit_project_form') %>');
<% end %>